### ISSUE TITLE
Exporting APIs

### ISSUE THREAD

**Issue by stewrutledge** [infor-cloud/xtendm3-maven-plugin#4]
There is a branch that seems to work with exporting APIs. Can this be pushed to a maven repository? I've tested it and it seems to work well enough

**Comment by ErfanY** [comment]
Thanks for bringing this up. Yes that is almost working but needs a few tweaks for it to be a bit more production-ready. We'll prioritize this as several people have asked for it.

**Comment by stewrutledge** [comment]
Do you have any timeframe for finishing up the work?

**Comment by stewrutledge** [comment]
@ErfanY What is it that's not working right? I would really like this functionality to be part of the standard maven plugin, I can help out with a merge request if you point me in the right direction.

**Comment by ErfanY** [comment]
@stewrutledge, it's being revived after some quiet period. You'll be seeing the functionality in the coming couple of weeks.

**Comment by ErfanY** [comment]
@stewrutledge this is now resolved. With version 0.1.4 you should be able to export transactions. Thanks!
