### ISSUE TITLE
0.1.4 Available in maven central

### ISSUE THREAD

**Issue by stewrutledge** [infor-cloud/xtendm3-maven-plugin#6]
@ErfanY I saw that the new version supporting exporting transactions has been pushed to github, but I'm not seeing it in maven central. Has it been published there as well?

**Comment by ErfanY** [comment]
Hi @stewrutledge, yes, new version get published to Maven central directly. Maven central usually takes from 10 minutes to an hour to synchronize. Below you can see the latest release information.

https://search.maven.org/artifact/com.infor.m3/xtendm3-maven-plugin/0.1.4/maven-plugin

On the README page there is an icon showing the latest released version, by clicking on that you will see the published version.
